### ISSUE TITLE
Dragonfly应用过程中通过配置文件怎么限流

### ISSUE THREAD

**Issue by sunny821** [dragonflyoss/dragonfly-archived#315]
你好，在应用过程中遇到问题：
通过dfdaemon读取/etc/dragonfly.conf  配置文件进行限流，
查了相关文档没有解决，能否给个配置模板

**Comment by Starnop** [comment]
Could you please provide more details? 
+ Which version? 
+ How do you configure it? 
+ What problems do you have? 
+ What are your expectations?
+ etc.

After that, we will supplement the appropriate documentations.

**Comment by Starnop** [comment]
Please refer to https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/config/config.go#L61, and we will supplement the appropriate documentation ASAP.
