### ISSUE TITLE
[question]关于supernode依赖tomcat的疑问

### ISSUE THREAD

**Issue by nonly** [dragonflyoss/dragonfly-archived#51]
1. 选用tomcat，而不用jetty是有什么考虑么？

**Comment by lowzj** [comment]
阿里内部多用tomcat，有很多针对tomcat的优化。后续我们打算简化supernode部署，去除单独部署tomcat，直接使用spring-boot做成fat-jar，如果您感兴趣，欢迎提供pull request^-^。

**Comment by nonly** [comment]
好的，了解

**Comment by lowzj** [comment]
@sunny821 是的，编译好之后直接 java -Dsupernode.baseHome=/tmp/dragonfly -jar supernode.jar 就可以启动，如果使用中有疑问，欢迎新建个issue。
